#!/bin/bash -e

year=${1:-`date +%Y`}
file="vaktija_$year"

pdftotext -layout -nopgbrk $file.pdf # generates $file.txt

./parse_vaktija.pl $year # generates $file.csv

sqlite3 ba.vaktija.android/assets/databases/vaktija.db <<EOF # update vaktija.db from $file.csv
delete from schedule;
.mode csv
.import vaktija_$year.csv schedule
EOF

# at the moment, adb install -r is not enough to reinstall the database, so full uninstall and install is performed
adb uninstall ba.vaktija.android.irfan & # async uninstall app
apktool b ba.vaktija.android # rebuild app
echo android | jarsigner -tsa http://timestamp.digicert.com ba.vaktija.android/dist/ba.vaktija.android.apk android
wait

adb install ba.vaktija.android/dist/ba.vaktija.android.apk & # asyinc install app
cp -v ba.vaktija.android/dist/ba.vaktija.android.apk /cygdrive/c/Users/root/Google\ Drive/ba.vaktija.android.irfan/ba.vaktija.android.irfan-$year.apk # copy to google drive
wait
