#!/bin/bash -e

pkg=ba.vaktija.android

updateapk () {
    apk=$(ls -t $pkg*apk | head -1)
    echo "Latest APK: [$apk]"
    rm -rf tmp
    apktool d "$apk" -o tmp
    sed -i "s/package=\"$pkg\"/package=\"$pkg.irfan\"/" tmp/AndroidManifest.xml
    sed -i "s/apkFileName: .*/apkFileName: ba.vaktija.android.apk/" tmp/apktool.yml
    echo "delete from locations where location != 'Beč (Džemat Bosna)';" | sqlite3 tmp/assets/databases/vaktija.db
    echo "update locations set location = 'Beč (Džemat Bosna)';" | sqlite3 tmp/assets/databases/vaktija.db
    sed -i 's/Beč (Džemat Bosna)/Beč (Džemat Bosna)/' $(grep -Ilr tmp)
    if [[ -e $pkg ]]; then
        rm -rf $pkg.bak
        mv $pkg $pkg.bak
    fi
    mv tmp $pkg
}

extract () {
    pdftotext -layout -nopgbrk $file.pdf # generates $file.txt
}

parse () {
    ./parse_vaktija.pl $year # generates $file.csv
}

updatedb () {
    sqlite3 $pkg/assets/databases/vaktija.db <<EOF # update vaktija.db from $file.csv
delete from schedule;
.mode csv
.import vaktija_$year.csv schedule
EOF
}

rebuild () {
    apktool b $pkg # rebuild app
    echo android | jarsigner -tsa http://timestamp.digicert.com $pkg/dist/$pkg.apk android
}

uninstall () {
    # at the moment, adb install -r is not enough to reinstall the database, so all uninstall and install is performed
    adb uninstall $pkg.irfan
}

install () {
    adb install $pkg/dist/$pkg.apk
}

reinstall () {
    uninstall
    install
}

copy () {
    cp -v $pkg/dist/$pkg.apk /d/GoogleDrive/Android/$pkg.irfan-$year.apk # copy to google drive
}

all () {
    extract
    parse
    updatedb
    rebuild
    copy
    echo "Done!"
    echo "Use '$0 reinstall' to reinstall the app to a connected phone"
}

unset cmd
for arg; do
    case $arg in
    [[:digit:]]*) year=$arg;;
    updateapk|extract|parse|updatedb|rebuild|uninstall|install|reinstall|copy|all) cmd=$arg;;
    *) echo -e "Invalid command [$arg], usage: $0 [year] [updateapk|extract|parse|updatedb|rebuild|[un|re]install|copy|all]\nDefault year is current year, default command is 'all'"; exit 1;;
    esac
done

[[ -n $year ]] || year=$(date +%Y)
file="vaktija_$year"
${cmd:-all}
